name: Laravel CI

on:
    push:
        branches: [ main, dev ]
    pull_request:
        branches: [ main, dev ]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
                    MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
                ports: ['3306:3306']
                options: --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
        - uses: actions/checkout@v4
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2 # Laravel 12 requires PHP 8.2+
            extensions: mbstring, dom, curl, libxml, zip, pcntl, pdo, pdo_mysql, sqlite, pdo_sqlite
        - run: composer install --prefer-dist --no-interaction
        - run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        - run: php artisan key:generate
        - run: php artisan migrate
        - run: npm install && npm run build
        - run: vendor/bin/phpunit
